### ISSUE TITLE
Create R versions of all Python exercises

### ISSUE THREAD

**Issue by ethanwhite** [ethanwhite/datacarp-semester-biology#1]

**Comment by brymz** [comment]
Expressions and Variables file names are 1 fewer than the `title:`.
For example the file Expressions-variables-1.md is titled Expressions and Variables 2.

**Comment by ethanwhite** [comment]
Feel free to rename appropriately. Just make sure that this names get updated anywhere they are used in the site. You can check this from the command line using something like:

`grep -r 'Expressions and Variables 2' *`

**Comment by brymz** [comment]
Do you want paragraph text left in one long sting to wrap within a window or broken up by some character width to form a block?

**Comment by ethanwhite** [comment]
Hard wrapped at 80 characters by default. Use your judgement in cases where the 80 character limit causes issues.

**Comment by ethanwhite** [comment]
Most decent text editors will have features that help with the hard wrapping.

**Comment by brymz** [comment]
Cool. I've just set my page width to be exactly 80 characters.

I add the line breaks to make it a 'hard' wrap?

**Comment by ethanwhite** [comment]
Yep, just hit Enter.

**Comment by brymz** [comment]
Done!

I have a list of the exercises I translated with current and old file names. Not sure it will be useful in the repo. If you think it will be, let me know where you'd like it dropped.
