### ISSUE TITLE
Issues with formatting in assignments

### ISSUE THREAD

**Issue by ethanwhite** [ethanwhite/datacarp-semester-biology#110]
Something got mixed up a little in the formatting of assignments. Compare:

* http://www.programmingforbiologists.org/assignments/programming-2/
* http://ethanwhite.github.io/datacarp-semester-biology/assignments/Python-2/

I think this is happening because the assignment name is capitalized. See the commit message for my solution to this:
https://github.com/ethanwhite/progbio/commit/79c5bbc44b8da4b988c9ad6bd41ffb0eda51a546

This means that the assignments need to start with lower case letters and the exercises start with capital letters. Yes, it is awful.

**Comment by brymz** [comment]
>> assignments need to start with lower case letters

After I lower case the assignments .md files, git does not seem to
recognize the change. There is "nothing to commit". When I `git rm
assignments/Python-1.md` it removes the 'assignments/python-1.md'

**Comment by brymz** [comment]
#113

**Comment by ethanwhite** [comment]
This works fine for me:

```bash
ethan@croryx:~/datacarp-semester-biology (gh-pages)$ git mv assignments/Python-1.md assignments/python-1.md
ethan@croryx:~/datacarp-semester-biology (gh-pages +)$ git status
On branch gh-pages
Your branch is up-to-date with 'origin/gh-pages'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	renamed:    assignments/Python-1.md -> assignments/python-1.md
````

**Comment by ethanwhite** [comment]
Are you on a Windows machine by chance? OS X is case sensitive (as is Linux).

**Comment by brymz** [comment]
I'm on OS X. The command line `git mv` worked. My first approach, just
renaming in the finder, was not recognized by git.

**Comment by brymz** [comment]
#114
