### ISSUE TITLE
R curriculum discussion

### ISSUE THREAD

**Issue by brymz** [ethanwhite/datacarp-semester-biology#12]
Re: Basic-Python2.md exercise comments. 
I include a mention of built-in functions in this exercise. I'm not sure that custom functions are required here, so maybe it would be best to introduce the idea in a later lesson.
We should introduce the various data classes (character, factor, numeric) and organizational structures (list, matrix, array, data frame) in an early lesson. Not sure where is the best place.

**Comment by ethanwhite** [comment]
I answered the question about custom functions in #11.

Core reading material from Data Carpentry and Software Carpentry should cover the introduction of the data types, and I suspect that types are also covered in one of the early Python lectures here that we'll be converting.

**Comment by brymz** [comment]
R does not seem to support combined operators (e.g., value += 1). Not sure if there is something similar to act as an alternate lesson.

**Comment by brymz** [comment]
How do we address modules / packages in R? The exercise Module-1 functions are built-in for R. We have discussed introducing `dplyr` and `ggplot`, which could definitely happen during the Database or Graphing topics later on.

**Comment by ethanwhite** [comment]
> R does not seem to support combined operators 

Just leave them out then

**Comment by ethanwhite** [comment]
> How do we address modules / packages in R? The exercise Module-1 functions are built-in for R. We have discussed introducing dplyr and ggplot, which could definitely happen during the Database or Graphing topics later on.

Yeah, basically we should introduce it the first time we need it, but have a focused problem like that one in that general area.
