### ISSUE TITLE
Ouput Pages ERROR '404: Page not found'

### ISSUE THREAD

**Issue by brymz** [ethanwhite/datacarp-semester-biology#126]
On both ethanwhite.github.io and my local host, the Output links return a 404: Page not found error.

I made sure that the links match the repo directory, so I;m not sure what's going on:
http://localhost:4000/solutions/Combining-the-basics-2-Python.txt
http://ethanwhite.github.io/solutions/Expressions-variables-1-R.txt

**Comment by ethanwhite** [comment]
This link is missing the repo name. This works:
http://ethanwhite.github.io/datacarp-semester-biology/solutions/Expressions-variables-1-R.txt

The reason it isn't working on localhost probably has to do with the baseurl handling.
