### ISSUE TITLE
Create outcome solutions for all exercises

### ISSUE THREAD

**Issue by ethanwhite** [ethanwhite/datacarp-semester-biology#2]
For both R and Python exercises we need a way to help both self-directed learners and university students check their work, but without giving them answers in code that they could just cut and paste for assignments. By showing them what the outcome of successfully running the code should look like, we both clarify the intent of the question and help students check their work. This also begins to introduce the benefits of testing.

The result here would be a new folder containing the "solutions" (i.e., what the output should look like) for each exercise, using the same naming structure as the associated exercise. Separate solutions will be necessary for R and Python since the details of the output won't be the same.

**Comment by brymz** [comment]
Do we want to treat image output differently than text output? For now, I am just going to save a .jpeg. in place of the .txt file. Future problems might require both text and image solution files.

**Comment by ethanwhite** [comment]
I think saving the .jpg makes the most sense for now and probably if we have problems that have both kinds of solutions we'll want to break them up into sub-problems (i.e., with numbered lists) if they aren't already, where each sub-problem has either text or image for the solution.

**Comment by brymz** [comment]
Done!
