### ISSUE TITLE
Translate Lists-2 to Lists-9

### ISSUE THREAD

**Issue by brymz** [ethanwhite/datacarp-semester-biology#39]
(Subissue #3) 

There are nine Lists exercises, but only Lists-1 is used in an assignment. Are we going to use them? 
Lists-2 and Lists-3 follow-up on Lists-1.
Lists-5 can introduce matrices.
Also, we should come up with an exercise to introduce lists. I use them when I have tables or lists of multiple data types that is entered from the script. Data with multiple data types in .csv get entered as  data frames.

***I've been meaning to have this 'what to do with unused exercises` chat more broadly.

**Comment by ethanwhite** [comment]
If I remember correctly I stopped using the extra lists exercises as I moved towards getting into data frames more quickly. I think we could just not translate a lot of those exercises unless you see things that would be useful in a different context.

**Comment by brymz** [comment]
>> we could just not translate a lot of those exercises
>> unless you see things that would be useful
I'm hesitant to make decisions like that because I'm fuzzy on the big
picture direction of the course. I think we have plenty of material. For
now, I'll avoid extra exercises until we have a better idea of what might
be missing. For instance, I flagged Loops-5 for a matrix exercise.

**Comment by ethanwhite** [comment]
Sounds good. I think you're always safe deciding not to translate something since that doesn't mean we can't go back and get it later. If it wasn't used last time I taught that's a pretty good sign that you could ignore it the first time through.

**Comment by brymz** [comment]
Roger that.
