### ISSUE TITLE
Translate Loops-4 & Loops-5

### ISSUE THREAD

**Issue by brymz** [ethanwhite/datacarp-semester-biology#42]
(Subissue #1)

Loops-4 seems like a useful extension of Loops-2 (old name: 'Loops-3')
Not sure what Loops-5 is about.

**Comment by ethanwhite** [comment]
Loops-5 is a stub for something I wanted to add eventually. No need to translate.

Loops-4 is designed to teach the standard:

```python
results = []
for stuff in things:
    results.append(dostuff(stuff))
```

concept, for which I'm sure there's an analog in R.

**Comment by brymz** [comment]
This abstract code chunk is brilliant! I've got to use it in my workshop this summer.
