### ISSUE TITLE
Add text/graphic solutions to Graphing and Statistics exercises

### ISSUE THREAD

**Issue by brymz** [ethanwhite/datacarp-semester-biology#59]
(Related PRs - #54, #56, #57, #58) 

How do we organize 'complex' solutions that include multiple image (.jpg) files? text and image files?

How do we organize output .csv files? name them by the exercise name? name them by the name given to the output file in the exercise?

**Comment by ethanwhite** [comment]
> How do we organize 'complex' solutions that include multiple image (.jpg) files? text and image files?

Off the top of my head... add an incremental part for each of the pieces. E.g., Basic-1-R-1.txt, Basic-1-R-2.jpg, Basic-1-R-3.jpg, but I'm open to other suggestions.

> How do we organize output .csv files? name them by the exercise name? name them by the name given to the output file in the exercise?

My initial thought is to base the names off of the exercise names for our solutions, but still have the students use the names given in the exercises. This will result in some detachment between the output solution and the actual solution the students are generating, but that can actually be useful in some cases (e.g., When grading I often accidentally overwrite the solution output file with the students output file).
