### ISSUE TITLE
Create database output solutions

### ISSUE THREAD

**Issue by ethanwhite** [ethanwhite/datacarp-semester-biology#6]
As in #2 it is useful to show the students what they should be getting as output.

**Comment by brymz** [comment]
See datacarp-semester-biology-solns PR # 44.
weecology/datacarp-semester-biology-exercise-solns#44

**Comment by brymz** [comment]
Make separate text files for querries to datacarp-semester-biology-soln
Make separate solution tables for datacaro-semester-biology/solutions.

**Comment by brymz** [comment]
#111
