### ISSUE TITLE
Advanced Topics

### ISSUE THREAD

**Issue by brymz** [ethanwhite/datacarp-semester-biology#72]
(sub issue #1; related to #46)

I have gone through the advanced course exercises and chosen a small(ish) set of topics and exercises I think would be worth considering for inclusion in the project. My idea is that these would provide an opportunity for classroom students to continue on from the course and have a direction for what is next if they are to continue pursuit of scientific programming and for at-home students to learn a handful of important, but a bit more complicated, skills.

After completing this list, #1 will be complete. We can also decide any or all are not worth it, and can be done with #1 now.

The list of exercises breaks into two categories.
1. New 'advanced' skills:
 -'Higher Order Functions 2'
 -Regular Expressions 1'
 -'Debugging'
 -'Tests 1' 
2. Challenging review:
 -'Basic 1'
 -'Basic 2'
 -'Making Choices 4'
 -'Scientific Python 3'

**Comment by ethanwhite** [comment]
Looks like a good list to me.
