### ISSUE TITLE
Create R versions of all Python code solutions

### ISSUE THREAD

**Issue by ethanwhite** [ethanwhite/datacarp-semester-biology#8]
Outside of the repository for the moment

**Comment by brymz** [comment]
What are your feelings on commenting and/or including the exercise language in the code solutions? I have found myself fairly liberal with additional explanatory text, so far.

**Comment by ethanwhite** [comment]
Good commenting including the exercise language is always a good idea. If it gets to be too much I'll let you know.

**Comment by brymz** [comment]
Most of the commenting ended up being direct quotes of the exercise to match up the code to the task. My later philosophy was that if I had to comment on my code solution then I wasn't writing it clear enough. Overall, there are relatively few in-line comments.

**Comment by brymz** [comment]
Done!
