### ISSUE TITLE
Update website structure to reflect single 1 semester class

### ISSUE THREAD

**Issue by ethanwhite** [ethanwhite/datacarp-semester-biology#85]

**Comment by brymz** [comment]
The .html are giving me a hard time when I try to edit them, either saying 'don't edit because you might break me' or asking me to change the file type to .rtfd. Can I ignore these messages? Do I need an html editor?

**Comment by ethanwhite** [comment]
Are these warnings/requests coming from your text editor?

No, html is just text so any text editor that doesn't do anything silly (like using special quotation marks or adding hidden markup should be fine. Definitely don't change the file type or extension.

**Comment by brymz** [comment]
The warnings are from 'text editor'. It shows the translated html (probably as an rtf), so I need to figure out how to work directly with the source text. Just checking in to be sure I know what I'm doing.

**Comment by ethanwhite** [comment]
I'd think about installing an alternative text editor for this sort of thing since "text editor" seems to like to mess with stuff. I've played around with Atom and really like it as a powerful but easy to use starting point:

https://atom.io/

**Comment by brymz** [comment]
The overall structure of the website had been revised to a single course. Some references to multiple courses might remain, like in the syllabus (#10) and schedule, though those issues should be taken care of during revision of those items.
