### ISSUE TITLE
Organizing page links by title always chooses Python exercises

### ISSUE THREAD

**Issue by brymz** [ethanwhite/datacarp-semester-biology#92]
(Subissue #85, Related PR #91)

assignments/index.md directs Jekyll to arrange find a list of exercises and arrange an assignments page using the exercise titles. Python and R assignments share titles, which means that currently the R assignments list is populated by Python exercises. Will have to code in the language from yaml here or change the titles throughout.

**Comment by ethanwhite** [comment]
`assignments/index.md` is actually hard coded links. They are based on names of assignments, but that shouldn't be a problem.

The individual assignments in the `assignments` folder do auto-generate based on title, but the code for that, which is located in `_includes/assignment.html` should be fairly easily modified to take a language variable that can then be added to the YAML in the individual assignments. I think that's probably the best way to go.

**Comment by brymz** [comment]
>> _includes/assignment.html should be fairly easily modified
Yep. Done.
